### ISSUE TITLE
Bluetooth devices that have been turned off can be scanned

### ISSUE THREAD

**Issue by LeiYao123** [andresperezmelo/print_bluetooth_thermal#16]
A Bluetooth printer was previously connected and now the power of the printer is directly turned off, but the Bluetooth device can already be scanned

Is there any way to prevent Bluetooth devices that have been turned off from being scanned

**Comment by LeiYao123** [comment]
Or add a function to scan all visible Bluetooth, and the user can filter it themselves

**Comment by andresperezmelo** [comment]
In Android, only previously paired devices are read, in iOS if nearby Bluetooth devices are scanned, in Android nearby devices are not read because Google's policy requires that location permission be requested, which affects the use of the device. plugin for applications that do not need that permission, I invite you to read the policy, https://developer.android.com/guide/topics/connectivity/bluetooth/find-bluetooth-devices

**Comment by hugeorange** [comment]
@andresperezmelo I understand,
My current requirement is to know if the paired devices are online. Do you have any good ideas?
I need to visually display the online status of Bluetooth devices that have been paired with the current phone in a list, as shown in the following figure
Because I am unable to obtain this list, I plan to use `fluent_ blue`,  This package searches for all visible Bluetooth devices and performs a screening with paired devices. I'm not sure if this is feasible
Your plugin can provide the ability to search for all Bluetooth devices, which is called `startDiscovery`
![image](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/18440746/09b124a6-34a9-40ff-90f5-ddeacfdafdb4)
![image](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/18440746/ee86fd98-470e-4013-a13b-38cd4398f59c)

**Comment by LeiYao123** [comment]
Thank you for your reply. I understand that scanning nearby online Bluetooth devices requires relevant permissions

I can now use this package(`https://pub.dev/packages/flutter_scan_bluetooth`) to search for nearby online Bluetooth devices, and then use `PrintBluetoothThermal.pairedBluetooths` to perform a layer of filtering to achieve the desired effect.

If your package comes with this feature built-in, it would be great
