### ISSUE TITLE
I can't print images

### ISSUE THREAD

**Issue by santosbj** [andresperezmelo/print_bluetooth_thermal#21]
Hi, this is great tool for printing, good work!. But, i have a problem printing images,

![image](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/66230272/c19eafaf-b881-44af-a744-1b2abdd3a300)

Even, after reducing quality, the result is the same.

This is my code.

![image](https://github.com/andresperezmelo/print_bluetooth_thermal/assets/66230272/95f629ff-796d-4452-a306-fb014f456abd)

Any idea?...

Thanks for your help.

**Comment by andresperezmelo** [comment]
That is a problem of the post code to print on the printer, the problem is not of our package, but of the package, at the time of creating the image may be that the printer is not interpreting well the post code from.

If you wish you can open an issue directly in the package repository.
[esc_pos_utils_plus](https://pub.dev/packages/esc_pos_utils_plus)

**Comment by santosbj** [comment]
Ok, thanks!
